### ISSUE TITLE
RadioLib license

### ISSUE THREAD

**Issue by jgromes** [tinytronix/SX126x#2]
Hello,

First of all, I want to say that your home automation LoRa gateways (as well as all the other home autmation devices) look really cool! 

That being said, in your SX126X library, you have obviously used large portions of [RadioLib](https://github.com/jgromes/RadioLib) code, which is developed by me. I don't intend to discourage people from doing that - quite the contrary, adapting code written by other people is one of the core ideas of open source development.

However, [RadioLib MIT License](https://github.com/jgromes/RadioLib/blob/master/license.txt) explicitly states that:

>The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

This is usually understood as including the original copyright holder's name in the appropriate section of  the software. Would it be possible to add this copyright notice, as to comply with RadioLib license?

Thank you very much.

**Comment by tinytronix** [comment]
Hey Jan,

this was by accident. I am new to github. And I missed the reaction window so they closed the repo.
My fault! Now after some days the repo is online again.  (just for an explanation why it took so long to react on your request)

I wanted to say thank you. Your work is really great and helped me a lot to understand the SX126X datasheet , the chip init sequence and saved days of time!

As you requested, I  created a file which includes your license:
https://github.com/tinytronix/SX126x/blob/master/RadioLibLicense.txt
And I also mentioned you in my intro:
https://github.com/tinytronix/SX126x

Hope this is ok!

**Comment by jgromes** [comment]
Thank you, this is perfectly fine. As I've said previously, I encourage others to adapt my code, but even on the Internet, there are still rules to follow ;). The usual way to modify code written by others on GitHub is to create a fork - the advantage is that it keeps the history of all files (same way Git does) and issues with licensing can be clarified easily.

I'll withdraw the DMCA claim once GitHub sends it back to me.

PS: You might want to update the contact email in library.json, the one that's in there doesn't seem to be working.
