### ISSUE TITLE
DRF1262T 30dbm Output Problem

### ISSUE THREAD

**Issue by berkerm4n** [tinytronix/SX126x#3]
On your code the output power limited to 22dbm. But module supports up to 30dbm(http://www.dorji.com/products-detail.php?ProId=71). Can you add support  for 30dbm output?

**Comment by tinytronix** [comment]
I investigated your request and I am a little bit confused about the datasheet. To me it seems that the DRF1262TL (30dBm) and the DRF1262T (which I use - 22dBm) have the same lora chip SX1262. The SX1262 datasheet says in chapter 13.4.4 SetTxParams: ...up to 22dBm.

So I am a little bit lost finding out where the 30dBm come from. In the  module flyer (http://www.dorji.com/products-detail.php?ProId=71) I found hints that the additional gain maybe comes from a hardware PA on the TL module? So currently I think that changing the driver will not have any effect at all.

Mabe someone has  an answer?
