### ISSUE TITLE
Arduino IDE: COM port is not available.

### ISSUE THREAD

**Issue by TinManAkshay** [tinytronix/SX126x#5]
Hi,

I am using your library in my custom board which has SX1262 chip and SAMD51 MCU on it and compiled the LoRA_TX example code. But i got the error COM port isnt available. 

Any clue why is like that by using this library?

Thanks,
Akshay

**Comment by tinytronix** [comment]
Unfortunatly I cannot tell why your Arduino IDE issues this error.
