### ISSUE TITLE
Couple of code errors

### ISSUE THREAD

**Issue by RecourseDesign** [tinytronix/SX126x#8]
SX126x.cpp
Line 70, ldro is not initialized.
Line 728, timeoutInMs * 0,015625 - should be "0.015625"

**Comment by freaklabs** [comment]
Just a clarification, the math is reversed. The timeout in milliseconds should be divided by 0.015625 to get the timeout value that gets written to the setTx command. 
![image](https://user-images.githubusercontent.com/1129352/190945435-fa39d746-07de-49f6-a8e2-daa8b716b0f0.png)

**Comment by RecourseDesign** [comment]
It's the "," instead of a "." - a lot of compilers fail with an error, or take it as 0.0
